name: smart_babyfoon
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  video_player: ^2.8.6
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.7
  lecle_yoyo_player: ^0.0.8
  path_provider: ^2.1.3
  flutter_sound: ^9.4.13
  permission_handler: ^11.3.1
  audioplayers: ^6.0.0
  cloud_firestore: ^4.17.5
  intl: any
  awesome_notifications: ^0.9.3+1
  workmanager: ^0.5.2
  firebase_messaging: ^14.9.4
  firebase_analytics: ^10.10.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true